[book]
authors = ["Pierre Zemb"]
language = "en"
multilingual = false
src = "src"
title = "the FoundationDB Book"

[output.html]
git-repository-url = "https://github.com/PierreZ/fdb-book"
site-url = "/fdb-book/"
additional-js =["mermaid.min.js", "mermaid-init.js"]

[preprocessor]
[preprocessor.mermaid]
command = "mdbook-mermaid"
