name: CI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - run: which mdbook || cargo install mdbook --locked --version 0.4.15
      - run: which mdbook-toc || cargo install mdbook-toc --locked --version 0.8.0
      - run: which mdbook-mermaid || cargo install mdbook-mermaid --locked --version 0.9.0
      - run: which mdbook-linkcheck || cargo install mdbook-linkcheck --locked --version 0.7.6

      - run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book